### ISSUE TITLE
network view does not display in safari

### ISSUE THREAD

**Issue by reimand0** [reimandlab/ActiveDriverDB#115]
only blank canvas is shown in Safari Version 10.1.1 (12603.2.4). Chrome Version 59.0.3071.115 is happy

**Comment by krassowski** [comment]
I confirmed this using browserstack (I do not own Mac and Safari is sadly no longer distributed for OSs other than MacOS). It seems to be [an issue](https://stackoverflow.com/questions/32048039/safari-compatible-css3-animation-on-an-svg-element?rq=1) with CSS3 transitions and svg elements out there for more than two years. Unfortunately I do not see any easy fix for that.

More precisely the issue is that the network, though rendered correctly is not positioned in the window so an user is unable to see it - translation and scale transformations do not work on Safari. I will investigate it further.

**Comment by krassowski** [comment]
I added a fallback mode so the network works again on Safari. I tested it using browserstack on Mavericks with Safari 7.1 and it worked well. Could you confirm if it works for you on 10.1.1 too, please?

**Comment by reimand0** [comment]
yes it looks to be working on my mac. thanks!
