### ISSUE TITLE
Advanced Search

### ISSUE THREAD

**Issue by idzneladze** [reimandlab/ActiveDriverDB#117]
I was wondering what is the exact purpose of the advanced search? Based on what I can tell, it seems like it allows the user to conduct a search based on an incomplete search query e.g. I can type in "TP5" and it will find TP53, TP53BP1, etc...

**Comment by krassowski** [comment]
Briefly, it shows more information on queried proteins and allows toggling
"only ptm muts" filter. There was a plan to add full filtering box like on
sequence or network view here too.

Much more important is the advanced mutations search - it allows vcf upload
as well as long text input hence it displays results for multiple mutations.

20 lip 2017 9:40 PM "idzneladze" <notifications@github.com> napisał(a):

I was wondering what is the exact purpose of the advanced search? Based on
what I can tell, it seems like it allows the user to conduct a search based
on an incomplete search query e.g. I can type in "TP5" and it will find
TP53, TP53BP1, etc...

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/reimandlab/ActiveDriverDB/issues/117>, or mute the
thread

**Comment by idzneladze** [comment]
Thank you for the explanation.
I will incorporate this information into the user manual.
